# Generated by Django 4.2.8 on 2025-03-22 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fb_leagues', '0003_leagueconfig_max_rookie_batting_apperances_and_more'),
        ('cpbl_players', '0003_cpblplayer_batting_appearances_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_type', models.CharField(choices=[('snake', 'Snake'), ('normal', 'Normal')], default='snake', max_length=10)),
                ('current_round', models.PositiveIntegerField(default=1)),
                ('current_pick', models.PositiveIntegerField(default=1)),
                ('max_round', models.PositiveIntegerField(default=20)),
                ('min_giveup_round', models.PositiveIntegerField(default=16)),
                ('top_n_round_for_draw', models.PositiveIntegerField(default=1)),
                ('is_complete', models.BooleanField(default=False)),
                ('draft_timeouts', models.PositiveIntegerField(default=60)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('league', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='draft_room', to='fb_leagues.league')),
            ],
        ),
        migrations.CreateModel(
            name='DraftUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField()),
                ('pick', models.PositiveIntegerField()),
                ('pre_draft', models.BooleanField(default=False)),
                ('pick_at_time', models.DateTimeField(blank=True, null=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='draft.draftroom')),
                ('new_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_picks', to='fb_leagues.fantasyteam')),
                ('ori_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_picks', to='fb_leagues.fantasyteam')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cpbl_players.cpblplayer')),
            ],
            options={
                'ordering': ['round', 'pick'],
                'unique_together': {('draft', 'round', 'pick')},
            },
        ),
    ]
