# Generated by Django 4.2.8 on 2025-03-22 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cpbl_players', '0005_cpblplayerboxpitcher_cpblplayerboxbatter'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RankingRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rank_type', models.CharField(choices=[('batter', 'Batter'), ('pitcher', 'Pitcher')], max_length=10)),
                ('year', models.PositiveIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('remark', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RankingPitcherDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(default=0)),
                ('mvp', models.IntegerField(default=0)),
                ('ip', models.FloatField(default=0)),
                ('wqs', models.IntegerField(default=0)),
                ('h', models.IntegerField(default=0)),
                ('sv', models.IntegerField(default=0)),
                ('so', models.IntegerField(default=0)),
                ('fip', models.FloatField(default=0)),
                ('era', models.FloatField(default=0)),
                ('whip', models.FloatField(default=0)),
                ('runs', models.IntegerField(default=0)),
                ('free_bases', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpbl_players.cpblplayer')),
                ('ranking_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pitcher_details', to='rankings.rankingrecord')),
            ],
        ),
        migrations.CreateModel(
            name='RankingBatterDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(default=0)),
                ('rrbi', models.IntegerField(default=0)),
                ('hr', models.IntegerField(default=0)),
                ('tb', models.IntegerField(default=0)),
                ('bbbbb', models.IntegerField(default=0)),
                ('avg', models.FloatField(default=0)),
                ('obp', models.FloatField(default=0)),
                ('isop', models.FloatField(default=0)),
                ('sb', models.IntegerField(default=0)),
                ('shf', models.IntegerField(default=0)),
                ('dopes', models.IntegerField(default=0)),
                ('mvp', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cpbl_players.cpblplayer')),
                ('ranking_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batter_details', to='rankings.rankingrecord')),
            ],
        ),
    ]
