# Generated by Django 4.2.8 on 2025-03-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_leagues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueconfig',
            name='max_players',
            field=models.PositiveIntegerField(default=6, help_text='聯盟中允許的最大玩家數'),
        ),
    ]
