# Generated by Django 4.2.8 on 2025-03-21 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_leagues', '0002_league_has_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='leagueconfig',
            name='max_rookie_batting_apperances',
            field=models.PositiveIntegerField(default=124),
        ),
        migrations.AddField(
            model_name='leagueconfig',
            name='max_rookie_pitching_innings3',
            field=models.PositiveIntegerField(default=120),
        ),
    ]
