# Generated by Django 4.2.8 on 2025-03-21 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_leagues', '0002_leagueconfig_max_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='is_public',
            field=models.BooleanField(default=True, help_text='是否為公開聯盟，所有人可瀏覽'),
        ),
        migrations.AlterField(
            model_name='leaguemembership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('mod', 'Moderator'), ('player', 'Player'), ('viewer', 'Viewer')], default='player', max_length=10),
        ),
    ]
