# Generated by Django 4.2.8 on 2025-03-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_leagues', '0003_league_is_public_alter_leaguemembership_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='invite_token_mod',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='league',
            name='invite_token_player',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='league',
            name='invite_token_viewer',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterUniqueTogether(
            name='fantasyteam',
            unique_together={('league', 'name')},
        ),
    ]
