# Generated by Django 4.2.8 on 2025-03-22 00:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_leagues', '0003_leagueconfig_max_rookie_batting_apperances_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='has_draft',
        ),
    ]
