# Generated by Django 4.2.8 on 2025-03-22 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_leagues', '0004_remove_league_has_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyteam',
            name='color',
            field=models.CharField(default='#000000', max_length=7),
        ),
    ]
