# Generated by Django 4.2.8 on 2025-03-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_leagues', '0005_fantasyteam_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='fantasyteam',
            name='text_color',
            field=models.CharField(default='#ffffff', max_length=7),
        ),
    ]
