# Generated by Django 4.2.8 on 2025-03-21 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CPBLPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.PositiveIntegerField(unique=True)),
                ('team_id', models.PositiveIntegerField()),
                ('jersey_number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('isForeign', models.BooleanField(default=False)),
                ('pitching_hand', models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('S', 'Switch')], max_length=1)),
                ('batting_hand', models.CharField(choices=[('L', 'Left'), ('R', 'Right'), ('S', 'Switch')], max_length=1)),
                ('main_pos', models.CharField(max_length=30)),
                ('batting_games', models.PositiveIntegerField(default=0)),
                ('pitching_games', models.PositiveIntegerField(default=0)),
                ('is_injured', models.BooleanField(default=False)),
                ('sp_games', models.PositiveIntegerField(default=0)),
                ('rp_games', models.PositiveIntegerField(default=0)),
                ('c_games', models.PositiveIntegerField(default=0)),
                ('_1b_games', models.PositiveIntegerField(default=0)),
                ('_2b_games', models.PositiveIntegerField(default=0)),
                ('_3b_games', models.PositiveIntegerField(default=0)),
                ('ss_games', models.PositiveIntegerField(default=0)),
                ('of_games', models.PositiveIntegerField(default=0)),
                ('lf_games', models.PositiveIntegerField(default=0)),
                ('cf_games', models.PositiveIntegerField(default=0)),
                ('rf_games', models.PositiveIntegerField(default=0)),
                ('mvp_counts', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CPBLPlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('games_played', models.PositiveIntegerField()),
                ('hits', models.PositiveIntegerField()),
                ('home_runs', models.PositiveIntegerField()),
                ('rbi', models.PositiveIntegerField()),
                ('player', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='cpbl_players.cpblplayer')),
            ],
        ),
    ]
