# Generated by Django 4.2.8 on 2025-03-21 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpbl_players', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpblplayer',
            name='isRookie',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cpblplayer',
            name='wasAbroad',
            field=models.BooleanField(default=False),
        ),
    ]
