# Generated by Django 4.2.8 on 2025-03-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpbl_players', '0002_cpblplayer_isrookie_cpblplayer_wasabroad'),
    ]

    operations = [
        migrations.AddField(
            model_name='cpblplayer',
            name='batting_appearances',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cpblplayer',
            name='pitching_innings3',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
