# Generated by Django 4.2.8 on 2025-03-22 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpbl_players', '0003_cpblplayer_batting_appearances_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cpblplayer',
            name='jersey_number',
            field=models.CharField(max_length=10),
        ),
    ]
