# Generated by Django 4.2.8 on 2025-03-22 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cpbl_players', '0004_alter_cpblplayer_jersey_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPBLPlayerBoxPitcher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_sno', models.CharField(max_length=20)),
                ('kind_code', models.CharField(default='A', max_length=2)),
                ('year', models.CharField(default='2024', max_length=4)),
                ('pitcher_name', models.CharField(max_length=100)),
                ('pitcher_uniform_no', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=10)),
                ('result', models.CharField(blank=True, max_length=10)),
                ('bs', models.CharField(max_length=1)),
                ('hold', models.IntegerField()),
                ('inning', models.IntegerField()),
                ('inning_div3', models.IntegerField()),
                ('pa', models.IntegerField()),
                ('pitch_count', models.IntegerField()),
                ('strike_count', models.IntegerField()),
                ('ball_count', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('hr', models.IntegerField()),
                ('sacrifice_hit', models.IntegerField()),
                ('sacrifice_fly', models.IntegerField()),
                ('bb', models.IntegerField()),
                ('ibb', models.IntegerField()),
                ('hbp', models.IntegerField()),
                ('so', models.IntegerField()),
                ('wp', models.IntegerField()),
                ('bk', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('earned_runs', models.IntegerField()),
                ('max_speed', models.IntegerField()),
                ('mvp', models.CharField(max_length=1)),
                ('error', models.IntegerField()),
                ('date', models.DateField()),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pitcher_stats', to='cpbl_players.cpblplayer')),
            ],
        ),
        migrations.CreateModel(
            name='CPBLPlayerBoxBatter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_sno', models.CharField(max_length=20)),
                ('kind_code', models.CharField(default='A', max_length=2)),
                ('year', models.CharField(default='2024', max_length=4)),
                ('hitter_name', models.CharField(max_length=100)),
                ('hitter_uniform_no', models.CharField(max_length=10)),
                ('pa', models.IntegerField()),
                ('ab', models.IntegerField()),
                ('mvp', models.CharField(max_length=1)),
                ('runs', models.IntegerField()),
                ('hits', models.IntegerField()),
                ('onebase_hits', models.IntegerField()),
                ('twobase_hits', models.IntegerField()),
                ('threebase_hits', models.IntegerField()),
                ('hr', models.IntegerField()),
                ('gs', models.IntegerField()),
                ('total_bases', models.IntegerField()),
                ('dp', models.IntegerField()),
                ('tp', models.IntegerField()),
                ('sacrifice_hit', models.IntegerField()),
                ('sacrifice_fly', models.IntegerField()),
                ('bb', models.IntegerField()),
                ('ibb', models.IntegerField()),
                ('hbp', models.IntegerField()),
                ('so', models.IntegerField()),
                ('sb', models.IntegerField()),
                ('cs', models.IntegerField()),
                ('as_runner_lobs', models.IntegerField()),
                ('as_hitter_lobs', models.IntegerField()),
                ('error', models.IntegerField()),
                ('date', models.DateField()),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batter_stats', to='cpbl_players.cpblplayer')),
            ],
        ),
    ]
